# See https://docs.gitlab.com/ee/ci/quick_start/index.html

image: python:3.9

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - pip install --user .
    - find ~/.local/

test-job1:
  stage: test
  script:
    - echo "This job tests something"
    - pwd
    - gdot

deploy-prod:
  stage: deploy
  script:
    - echo "The thing on $CI_COMMIT_BRANCH branch is done."
