#!/bin/sh
# gido

if [ "$1" = "--help" ]
then
    printf 'gido: show git using dot; options are passed to `git log`\n'
    exit 0
fi

printf 'digraph G {\n'
git log --no-patch '--pretty=%h %p -- %D' "$@" |
  awk '{
    label = $1
    # Rename nodes so that they start with S, making them lexique.
    for(i=1; $i != "--"; i+=1){ $i = "S"$i }
    # Node label
    print $1, "[ label = \042" label "\042 ]"
    # An edge for each parent
    for(i=2; $i!="--"; i+=1) {
      print $1, "->", $i
    }
    i += 1
    # An exterior label for each branch/tag
    while(i<=NF) {
      print $1, "[ xlabel = \042" $i "\042 ]"
      i += 1
    }
  }'
printf '}\n'
